// client/src/components/App.jsx
import React from 'react';
import axios from 'axios';

import Animal from './Animal';
import Birthday from './Birthday';
import Fruit from './Fruit';
import Emo from './Emo';
import Selection from './Selection';
import Result from './Result';

class App extends React.Component {
  constructor() {
    super();
    this.state = {
      emotion: '',
      normalEmotion: '',
      emoEmotion: '',
      animal: '',
      petName: '',
      birthday: '',
      fruit: '',
      sugar: '',
      emo: false,
      result: false,
      mainResult: '',
      emoResult: '',
    };
    this.handleSubmit = this.handleSubmit.bind(this);
    this.getEmotion = this.getEmotion.bind(this);
    this.checkAll = this.checkAll.bind(this);
    this.postAll = this.postAll.bind(this);
    this.logBirthday = this.logBirthday.bind(this);
    this.logPet = this.logPet.bind(this);
    this.logFruit = this.logFruit.bind(this);
    this.logResult = this.logResult.bind(this);
    this.selectChange = this.selectChange.bind(this);
  }

  handleSubmit() {
    const { emo } = this.state;
    this.getEmotion(emo);
    this.checkAll();
  }

  getEmotion(emo) {
    axios.get('/submit/emotion')
      .then((res) => {
        const randomEmotion1 = res.data[Math.floor(Math.random() * res.data.length)].word;
        this.setState({ emotion: randomEmotion1, normalEmotion: randomEmotion1 });
      })
      .catch((error) => {
        console.error('error in get emotion', error);
      });
    axios.get('/submit/emotion/emo')
      .then((res) => {
        const randomEmotion2 = res.data[Math.floor(Math.random() * res.data.length)].word;
        this.setState({ emoEmotion: randomEmotion2 });
      })
      .catch((error) => {
        console.error('error in get emotion', error);
      });
  }

  postAll() {
    const {
      emotion, normalEmotion, emoEmotion, animal, petName, birthday, fruit, sugar, result,
    } = this.state;

    const theEmotion = emotion || 'chief';
    const theEmo = emoEmotion || 'sadly';
    const thePetName = petName || 'mikey';
    const theSugar = sugar || '3000';
    const mainResult = `${theEmotion}_${thePetName}_${theSugar}`;
    const emoResult = `_xXx_${theEmo}_${thePetName}_666_xXx_`;

    axios.post('/submit/post', {
      emotion, normalEmotion, emoEmotion, animal, petName, birthday, fruit, sugar, result, mainResult, emoResult,
    })
      .catch((error) => {
        console.error('error in submit post', error);
      });
    this.setState({ result: true, mainResult, emoResult });
  }

  checkAll() {
    const { birthday, fruit, animal } = this.state;
    const checkIt = {
      method: 'get',
      url: '/submit/get',
      params: { birthday, fruit, animal },
    };
    axios(checkIt)
      .then((res) => {
        if (res.data[0]) {
          this.setState({ result: true, emotion: res.data[0].emotion, normalEmotion: res.data[0].normalEmotion, emoEmotion: res.data[0].emoEmotion, petName: res.data[0].petName, sugar: res.data[0].sugar, mainResult: res.data[0].mainResult, emoResult: res.data[0].emoResult });
        } else {
          this.postAll();
        }
      })
      .catch((error) => {
        console.error('error in check it', error);
      });
  }

  logBirthday(birthday) {
    const { emo } = this.state;
    this.getEmotion(emo);
    this.setState({ birthday, result: false });
  }

  logPet(animal, petName) {
    this.setState({ animal, petName, result: false });
  }

  logFruit(fruit, sugar) {
    this.setState({ fruit, sugar, result: false });
  }

  logResult(mainResult, emoResult) {
    this.setState({ mainResult, emoResult });
  }

  selectChange() {
    const { emo, normalEmotion, emoEmotion } = this.state;
    if (emo) {
      this.setState({ emo: false, emotion: normalEmotion });
    } else {
      this.setState({ emo: true, emotion: emoEmotion });
    }
  }

  render() {
    const {
      emotion, animal, petName, fruit, sugar, birthday, emo, result, mainResult, emoResult,
    } = this.state;
    return (
      <>
        <div id="header">
          name generator
        </div>
        <div id="main">
          <h4>Your Birthday:</h4>
          <Birthday logBirthday={this.logBirthday} />
          <h4>Favorite Animal:</h4>
          <Animal logPet={this.logPet} birthday={birthday} />
          <h4>Pick a Fruit:</h4>
          <Fruit logFruit={this.logFruit} />
          <Selection birthday={birthday} animal={animal} fruit={fruit} submit={this.handleSubmit} result={result} />
          <Emo selectChange={this.selectChange} emo={emo} />
          {result ? <Result emo={emo} mainResult={mainResult} emoResult={emoResult} />
            : undefined}
        </div>
      </>
    );
  }
}

export default App;

// client/src/components/App.vue
<template>
  <div class="wrapper">
    <div id="header">NAME GENERATOR</div>
    <div id="main">
      <h4>Your Birthday:</h4>
      <Birthday @logBirthday="logBirthday" />
      <h4>Favorite Animal:</h4>
      <Animal :birthday="birthday" @logAnimal="logAnimal" @logPet="logPet" />
      <h4>Pick a Fruit:</h4>
      <Fruit @logFruit="logFruit" @logSugar="logSugar" />
      <Selection :birthday="birthday" :animal="animal" :fruit="fruit" />
      <form @submit.prevent="checkAll">
        <button id="submit-button-main" :disabled="isFilled" type="submit">
          Submit
        </button>
      </form>
      <h4>
        Emo Mode:
        <input v-model="emo" type="checkbox" />
      </h4>
      <h3>Your New Name:</h3>
      <div v-if="emo" id="result">
        <div id="new-name">
          <h2 v-if="finalResults">{{ emoResult }}</h2>
        </div>
      </div>
      <div v-else id="result">
        <div id="new-name">
          <h2 v-if="finalResults">{{ mainResult }}</h2>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';
import Animal from './Animal.vue';
import Birthday from './Birthday.vue';
import Fruit from './Fruit.vue';
import Selection from './Selection.vue';

export default {
  components: {
    Animal,
    Birthday,
    Fruit,
    Selection,
  },

  data() {
    return {
      emotion: '',
      normalEmotion: '',
      emoEmotion: '',
      animal: '',
      petName: '',
      birthday: '',
      fruit: '',
      sugar: '',
      emo: false,
      mainResult: '',
      emoResult: '',
    };
  },

  computed: {
    isFilled() {
      if (
        this.birthday.length !== 0 &&
        this.animal.length !== 0 &&
        this.fruit.length !== 0
      ) {
        return false;
      }
      return true;
    },

    finalResults() {
      if (this.mainResult.length !== 0 && this.emoResult.length !== 0) {
        return true;
      }
      return false;
    },
  },

  methods: {
    getEmotion() {
      axios
        .get('/submit/emotion')
        .then((res) => {
          const random = Math.floor(Math.random() * res.data.length);
          const randomEmotion1 = res.data[random].word;
          this.emotion = randomEmotion1;
          this.normalEmotion = randomEmotion1;
        })
        .catch((error) => {
          console.error('error in get emotion', error);
        });
      axios
        .get('/submit/emotion/emo')
        .then((res) => {
          const random = Math.floor(Math.random() * res.data.length);
          const randomEmotion2 = res.data[random].word;
          this.emoEmotion = randomEmotion2;
        })
        .catch((error) => {
          console.error('error in get emotion', error);
        });
    },

    postAll() {
      const theEmotion = this.emotion || 'chief';
      const theEmo = this.emoEmotion || 'sadly';
      const thePetName = this.petName || 'mikey';
      const theSugar = this.sugar || '3000';
      const mainResult = `${theEmotion}_${thePetName}_${theSugar}`;
      const emoResult = `_xXx_${theEmo}_${thePetName}_666_xXx_`;
      this.mainResult = mainResult;
      this.emoResult = emoResult;
      axios
        .post('/submit/post', {
          emotion: this.emotion,
          normalEmotion: this.normalEmotion,
          emoEmotion: this.emoEmotion,
          animal: this.animal,
          petName: this.petName,
          birthday: this.birthday,
          fruit: this.fruit,
          sugar: this.sugar,
          mainResult,
          emoResult,
        })
        .catch((error) => {
          console.error('error in submit post', error);
        });
    },

    checkAll() {
      const checkIt = {
        method: 'get',
        url: '/submit/get',
        params: {
          birthday: this.birthday,
          fruit: this.fruit,
          animal: this.animal,
        },
      };
      axios(checkIt)
        .then((res) => {
          if (!res.data[0]) {
            this.postAll();
          } else {
            this.emotion = res.data[0].emotion;
            this.normalEmotion = res.data[0].normalEmotion;
            this.emoEmotion = res.data[0].emoEmotion;
            this.petName = res.data[0].petName;
            this.sugar = res.data[0].sugar;
            this.mainResult = res.data[0].mainResult;
            this.emoResult = res.data[0].emoResult;
          }
        })
        .then(() => {
          this.animal = '';
          this.birthday = '';
          this.fruit = '';
        })
        .catch((error) => {
          console.error('error in check it', error);
        });
    },

    logBirthday(birthday) {
      this.getEmotion(this.emo);
      this.birthday = birthday;
    },

    logAnimal(animal) {
      this.animal = animal;
    },

    logPet(petName) {
      this.petName = petName;
    },

    logFruit(fruit) {
      this.fruit = fruit;
    },

    logSugar(sugar) {
      this.sugar = sugar;
    },

    logResult(mainResult, emoResult) {
      this.mainResult = mainResult;
      this.emoResult = emoResult;
    },
  },
};
</script>

<style lang="stylus">
*, *::before, *::after
  box-sizing border-box

html, body
  font 16px/1.2 BlinkMacSystemFont, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif
  padding 10px
  background-color lightgray

h2, h3, h4, h5, h6
  padding 5px 0 5px 0
  margin 5px 0 5px 0

.wrapper
  background-color black
  color white
  width 500px
  margin auto
  padding 40px
  box-shadow 10px 10px green

#header
  font-size 24px
  font-weight 900
  text-align center
  padding-bottom 20px

#main
  display flex
  flex-direction column
  align-items center

form
  margin-bottom 20px

select
  height 30px

input[type="text"]
  width 200px
  height 30px
  padding 10px
  border 1px solid #777

.submit-button
  height 30px

#submit-button-main
  width 300px
  height 50px
  margin 20px 0 10px 0
  padding 10px 20px 10px 20px
  align-self center

#result
  height 50px
  text-shadow 4px 4px green
</style>
